### ISSUE TITLE
Over-cloning in code which results in unintended behaviour

### ISSUE THREAD

**Issue by RoMeAh** [BlazifyOrg/blazescript#2]
```
class Main {
    @ property
    var a = 0;

    @ constructor
    fun() => { 
        a = a + 1;
        sum_to_a(5);
    }

    @ method
    fun sum_to_a(new_a) => {
    	a = new_a;
    }
}

var main_ins = new Main();
println(main_ins);

main_ins.sum_to_a(4);
println(main_ins);
```
The output will be something like
```shell
{
     a: 5,
     sum_to_a: fun sum_to_a(new_a)
}
Runtime Error: Variable not found to be reassigned
File examples/main.bzs, line 13

 
    a = new_a
    ^^^^^^^^^^
Traceback (most recent call last):
    at Function<sum_to_a>
    at examples/main.bzs
```

Here what happens is that after the class in initialized i.e the constructor is ran it returns a Object of the properties and it's methods but this results in popping of the context, so when the function is accessed after initialization, the method is returned but the context which consisted of the properties and other methods in not present.
[The Class Initialization  related code](https://github.com/BlazifyOrg/blazescript/blob/main/src/core/interpreter/value.rs#L381)

Any help or pull requests are greatly appreciated...

**Comment by RoMeAh** [comment]
Logic has been fixed in the commit https://github.com/BlazifyOrg/blazescript/commit/012be9436619df98e1f212863c1ec69c61af837b but rust is still screaming with the errors of 
```shell
error[E0507]: cannot move out of a shared reference
   --> src/core/interpreter/interpreter.rs:363:35
    |
363 |                     object = Some(*self.ctx.last().unwrap().symbols.get("soul").unwrap());
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because value has type `Symbol`, which does not implement the `Copy` trait

error[E0382]: borrow of moved value: `properties_e`
   --> src/core/interpreter/value.rs:567:17
    |
548 |             let mut properties_e: HashMap<String, Value> = HashMap::new();
    |                 ---------------- move occurs because `properties_e` has type `HashMap<String, Value>`, which does not implement the `Copy` trait
...
556 |                         properties: properties_e,
    |                                     ------------ value moved here
...
567 |                 properties_e.insert(k.to_string(), e_v.val.unwrap());
    |                 ^^^^^^^^^^^^ value borrowed here after move

error[E0507]: cannot move out of a shared reference
   --> src/core/interpreter/value.rs:583:24
    |
583 |             let soul = inter.ctx.last().unwrap().symbols.get("soul").unwrap().value;
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |                        |
    |                        move occurs because value has type `Value`, which does not implement the `Copy` trait
    |                        help: consider borrowing here: `&inter.ctx.last().unwrap().symbols.get("soul").unwrap().value`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0382, E0507.
For more information about an error, try `rustc --explain E0382`.
error: could not compile `blazescript`
```

**Comment by RoMeAh** [comment]
In the latest commit the Object property modifying has been fixed but rust is back again at screaming
```shell
error[E0308]: mismatched types
   --> src/core/interpreter/interpreter.rs:605:29
    |
605 |                 return Some(sym.unwrap());
    |                             ^^^^^^^^^^^^ expected struct `Symbol`, found `&Symbol`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `blazescript`
```

**Comment by paulotten** [comment]
Dereference it?

```
return Some(*sym.unwrap());
```

**Comment by RoMeAh** [comment]
Dereferencing will give a error as the value gets moved, we can get around by cloning but that will result in unintended functioning of code.

**Comment by paulotten** [comment]
Side effects of changing your return type to `Option<&Symbol>`?

**Comment by RoMeAh** [comment]
If you are free, maybe you could clone the repository and check it out yourself as there are a lot of side-effects.

**Comment by RoMeAh** [comment]
#3 fixed the compiler errors but the runtime bug isn't fixed yet.

**Comment by RoMeAh** [comment]
**Cloning we are doing right now that we can't afford**
1. [`Symbol` `Value` cloning](https://github.com/BlazifyOrg/blazescript/blob/main/src/utils/symbol.rs#L12)
2. [`HashMap` `get` cloning](https://github.com/BlazifyOrg/blazescript/blob/main/src/core/interpreter/interpreter.rs#L605)
3. [`soul` cloning in methods](https://github.com/BlazifyOrg/blazescript/blob/main/src/core/interpreter/interpreter.rs#L363)
4. [Clone of properties in `soul` object during class initialization](https://github.com/BlazifyOrg/blazescript/blob/main/src/core/interpreter/interpreter.rs#L363)

**Comment by paulotten** [comment]
I added some of those.

The alternative the compiler was suggesting was lifetimes. I don't think that fits well with implementing a scripting language. We aren't likely to know the lifetime of a script object when we compile the interpreter.

I'm thinking we should be looking at [Rc](https://doc.rust-lang.org/std/rc/struct.Rc.html) or [Arc](https://doc.rust-lang.org/std/sync/struct.Arc.html) depending on if we want to support threading.

**Comment by RoMeAh** [comment]
This issue is not high priority right now as we are moving to a Bytecode Generator and a VM, but the context issue may still be valid for the VM interpreting we need internal mutability of the strutcts from multiple places.
